export const cantataTheme = {
  bgLinen: '#FAF3E8',
  bgCream: '#F5EFE6',
  bgParchment: '#EDE5D8',
  bgWhite: '#FFFFFF',
  cinnamon: '#A0623D',
  cinnamonMd: '#B5744E',
  cinnamonLt: '#C98B65',
  cinnamonBg: '#F2E6DB',
  mint: '#3FA88C',
  mintMd: '#4DB89B',
  mintLt: '#E5F4EE',
  mintBorder: '#B8E0D5',
  lavender: '#C8C4E0',
  lavBg: '#EFEEFC',
  textInk: '#2B2B2B',
  textBody: '#4A443D',
  textSub: '#7A7468',
  textGhost: '#AEA79E',
  line: '#E5DDD0',
  lineMd: '#D8CEBE',
  serif: "'Playfair Display', Georgia, serif",
  sans: "'DM Sans', system-ui, sans-serif",
  rXs: '6px',
  rSm: '10px',
  rMd: '16px',
  rLg: '22px',
  rXl: '30px',
  rPill: '999px',
  macroTransition: '300ms',
  microTransition: '100ms',
} as const;
